// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const environment = process.env.ENVIRONMENT || "dev";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: environment === "dev" ? env("LOCAL_DATABASE_URL") : env("DOCKER_DATABASE_URL"),
  },
});


