version: '3.8'

services:
  db:
    image: mariadb:11
    container_name: metari_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
      # - ./metari.sql:/docker-entrypoint-initdb.d/metari.sql
    ports:
      - "${MYSQL_PORT:-3306}:3306"

  phpmyadmin:
    image: phpmyadmin:5.2.3-apache
    container_name: metari_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"

volumes:
  db_data: